import { chromium } from 'playwright';
import http from 'http'; import fs from 'fs';
const [,, F, AT, OUT] = process.argv;
const srv = http.createServer((q, r) => { const size = fs.statSync(F).size; const range = q.headers.range; if (range) { const m = /bytes=(\d*)-(\d*)/.exec(range); const a = +m[1] || 0, z = m[2] ? +m[2] : size - 1; const fd = fs.openSync(F, 'r'); const buf = Buffer.alloc(z - a + 1); fs.readSync(fd, buf, 0, buf.length, a); fs.closeSync(fd); r.writeHead(206, { 'Content-Type': 'video/mp4', 'Content-Range': `bytes ${a}-${z}/${size}`, 'Content-Length': buf.length, 'Accept-Ranges': 'bytes', 'Access-Control-Allow-Origin': '*' }); r.end(buf); return; } r.writeHead(200, { 'Content-Type': 'video/mp4', 'Content-Length': size, 'Accept-Ranges': 'bytes', 'Access-Control-Allow-Origin': '*' }); fs.createReadStream(F).pipe(r); }).listen(8820);
const b = await chromium.launch({ channel: 'chrome', args: ['--autoplay-policy=no-user-gesture-required'] }); const p = await b.newPage();
await p.setContent('<video id="v" crossorigin="anonymous" muted src="http://127.0.0.1:8820/x.mp4"></video><canvas id="c"></canvas>');
await p.waitForFunction(() => document.getElementById('v').readyState >= 2, null, { timeout: 60000 });
const png = await p.evaluate((AT) => new Promise(async done => { const v = document.getElementById('v'); v.playbackRate = 8; await v.play(); const iv = setInterval(() => { if (v.currentTime >= AT) { clearInterval(iv); v.pause(); const c = document.getElementById('c'); c.width = v.videoWidth; c.height = v.videoHeight; c.getContext('2d').drawImage(v, 0, 0); done([c.toDataURL('image/jpeg', 0.85), v.videoWidth + 'x' + v.videoHeight, v.duration.toFixed(1)]); } }, 50); }), +AT);
fs.writeFileSync(OUT, Buffer.from(png[0].split(',')[1], 'base64')); console.log(png[1], png[2]);
await b.close(); srv.close();
